module.exports = {
  projects: [
    '<rootDir>/libs/api/config',
    '<rootDir>/libs/api/model',
    '<rootDir>/libs/api/router',
    '<rootDir>/libs/api/restify',
    '<rootDir>/libs/api/database',
    '<rootDir>/libs/api/schema/props',
    '<rootDir>/libs/api/schema/node',
    '<rootDir>/libs/api/drivers/neo4j',
    '<rootDir>/libs/api/drivers/graphql',
    '<rootDir>/libs/api/drivers/mongoose',
    '<rootDir>/libs/api/logger',
    '<rootDir>/libs/tools/eslint-config-codelab',
    '<rootDir>/libs/tools/plugins/codelab',
    '<rootDir>/libs/shared/common',
    // '<rootDir>/libs/shared/interface/node',
    // '<rootDir>/libs/shared/interface/graph',
    // '<rootDir>/libs/shared/interface/props',
    // '<rootDir>/libs/shared/interface/model',
    // '<rootDir>/libs/shared/interface/tree',
    // '<rootDir>/libs/shared/interface/component',
    '<rootDir>/libs/core/graph',
    '<rootDir>/libs/core/model',
    '<rootDir>/libs/core/props',
    '<rootDir>/libs/core/node',
    '<rootDir>/libs/core/traversal',
    '<rootDir>/libs/core/tree',
    '<rootDir>/libs/shared/utils',
    '<rootDir>/libs/shared/event',
    '<rootDir>/apps/web',
    '<rootDir>/libs/core/renderer',
    '<rootDir>/libs/state/app',
    '<rootDir>/libs/state/node',
    '<rootDir>/libs/state/modal',
    '<rootDir>/libs/ui/antd',
    '<rootDir>/libs/ui/d3',
    '<rootDir>/libs/ui/component',
    '<rootDir>/libs/ui/hoc',
    '<rootDir>/libs/state/apollo',
    '<rootDir>/apps/api/gateway',
    '<rootDir>/apps/api/services/props',
    '<rootDir>/apps/api/services/user',
    '<rootDir>/libs/api/prisma',
    '<rootDir>/libs/state/ui',
    '<rootDir>/apps/api/services/graph',
    '<rootDir>/libs/api/services/props',
    '<rootDir>/libs/api/services/node',
    '<rootDir>/apps/api/external',
  ],
}
