# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

# Success notification is added to end of workflow, while failure notification is added to end of each job.

# Don't run on master
filters-dev: &filters-dev
  filters:
    branches:
      only: /^.*$/
#      ignore: /^master$/
#    tags:
#      ignore: /^staging-/

# Run on master only
filters-staging: &filters-staging
  filters:
    branches:
#      only: /^master$/
      # turn off for now
      only: /^never$/
#    tags:
#      only: /^staging-/

executor-params: &executor-params
  parameters:
    e:
      type: executor
      default: machine-ubuntu
  executor: << parameters.e >>

executor-config: &executor-config
  environment:
    GITHUB_ANTON: artonio
    SLACK_ANTON: U01DSP39DME
    GITHUB_VIEN: VienNguyen24hdev
    SLACK_VIEN: UBPECLD4P
    GITHUB_WEBBER: webberwang
    SLACK_WEBBER: U0J401GAH
    GITHUB_ALEX: aburtsev
    SLACK_ALEX: U01APQT5XCH
    SLACK_CHANNEL_UPDATE: CQVPNKS8K
    COLOR_SUCCESS: '#b7eb8f'
    COLOR_FAILURE: '#ffccc7'
    NODE_OPTIONS: --max_old_space_size=8192
    NODE_ENV: production
  working_directory: ~/app

version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  machine-ubuntu:
    <<: *executor-config
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:202008-01
    resource_class: large
  docker-node:
    <<: *executor-config
    docker:
      - image: circleci/node:14-browsers
    resource_class: large

commands:
  setup-env:
    description: 'Setup env'
    steps:
      - run:
          name: 'Setup node options'
          command: |
            echo 'export NODE_OPTIONS=$NODE_OPTIONS' >> $BASH_ENV
            source $BASH_ENV
            echo $NODE_OPTIONS
      - run:
          name: 'Setup GIT_COMMIT_MSG'
          command: |
            echo 'export GIT_COMMIT_MSG=$(git log --format="format:%s" -n 1 ${CIRCLE_SHA1})' >> $BASH_ENV
            source $BASH_ENV
            echo $GIT_COMMIT_MSG
      - run:
          # Github user who triggered Circle is the slack mention user
          name: 'Setup SLACK_USER'
          command: |
            if [ $CIRCLE_USERNAME == $GITHUB_VIEN ]; then
              echo 'export SLACK_USER=${SLACK_VIEN}' >> $BASH_ENV
            elif [ $CIRCLE_USERNAME == $GITHUB_ALEX ]; then
              echo 'export SLACK_USER=${SLACK_ALEX}' >> $BASH_ENV
            else
              echo 'export SLACK_USER=${SLACK_WEBBER}' >> $BASH_ENV
            fi
            source $BASH_ENV
            echo $SLACK_USER

  setup-workspace:
    description: 'Setup workspace'
    steps:
      - checkout
      - setup-env
      - attach_workspace:
          at: ..

  yarn-install-dev:
    steps:
      - restore_cache:
          name: 'Restore Yarn cache'
          keys:
            - dep-cache-dev-{{ checksum "yarn.lock" }}
            # https://discuss.circleci.com/t/circle-2-0-caching-is-too-limited-to-be-very-useful/11694
            - dep-cache-dev-
      - run:
          name: 'Install NPM packages'
          command: yarn install --frozen-lockfile --prod=false
      - save_cache:
          name: 'Save cache'
          key: dep-cache-dev-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/app/node_modules

  yarn-install-prod:
    description: 'Install prod dependencies'
    steps:
      - restore_cache:
          name: 'Restore Yarn cache'
          keys:
            - dep-cache-prod-{{ checksum "yarn.lock" }}
            - dep-cache-prod-
      - run:
          name: 'Install NPM packages'
          command: yarn install --frozen-lockfile --prod=true
      - save_cache:
          name: 'Save cache'
          key: dep-cache-prod-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/app/node_modules

  notify-failure:
    steps:
      - slack/status:
          fail_only: true
          channel: $SLACK_CHANNEL_UPDATE
          mentions: $SLACK_USER

jobs:
  install-and-build-workspace:
    <<: *executor-params
    steps:
      - setup-env
      - checkout
      - yarn-install-dev
      - run:
          name: 'Build CI'
          command: make build-ci
      - persist_to_workspace:
          root: ..
          paths:
            - app/node_modules
            - app/dist
      - notify-failure

  lint:
    <<: *executor-params
    environment:
      CIRCLE_BASE_REVISION: <<pipeline.git.base_revision>>
    steps:
      - setup-workspace
      - run: make lint-eslint
      - run: make lint-commit-ci
      - notify-failure

  test:
    <<: *executor-params
    steps:
      - setup-workspace
      - run: make test-ci
      - notify-failure

  notify-success:
    <<: *executor-params
    steps:
      - setup-env
      - slack/notify:
          channel: $SLACK_CHANNEL_UPDATE
          color: $COLOR_SUCCESS
          mentions: $SLACK_USER
          message: >
            *Status*: :white_check_mark: Success \n
            *Branch*: << pipeline.git.branch >> \n
            *Message*: $GIT_COMMIT_MSG \n

  deploy-app:
    <<: *executor-params
    steps:
      - setup-workspace
      - yarn-install-prod
      - run:
          name: 'Build Docker image'
          command: make docker-build
      - run:
          name: 'Docker login'
          command: echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
      - run:
          name: 'Push Docker image'
          command: make docker-push

  notify-failure:
    <<: *executor-params
    steps:
      - setup-env
      - slack/status:
          fail_only: true
          channel: $SLACK_CHANNEL_UPDATE
          mentions: $SLACK_USER

workflows:
  app-dev:
    jobs:
      - install-and-build-workspace:
          <<: *filters-dev
          e: docker-node
      - lint:
          <<: *filters-dev
          e: docker-node
          requires:
            - install-and-build-workspace
      - test:
          <<: *filters-dev
          e: docker-node
          requires:
            - install-and-build-workspace
      - notify-success:
          <<: *filters-dev
          e: docker-node
          requires:
            - lint
            - test

  app-staging:
    jobs:
      - install-and-build-workspace:
          <<: *filters-staging
      - deploy-app:
          <<: *filters-staging
          context: credentials-docker
          requires:
            - install-and-build-workspace
